server:
  port: 8080

spring:
  application:
    name: backend
    security:
      jwt:
        secret: mysecretkeydfsssssssssssssssssssssssssssseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewwwwwwwwwwwwww
        expiration: 6000000 # in seconds
        refresh-token:
          expiration: 60000 # in seconds


  datasource:
    url: jdbc:postgresql://localhost:5433/dbtbm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: test

  logging:
    level:
      org.springframework.r2dbc: DEBUG
      io.r2dbc: DEBUG

constant:

